# Generated by Django 2.1.4 on 2018-12-12 17:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='the_json',
            field=jsonfield.fields.JSONField(),
        ),
    ]
