# Generated by Django 2.1.4 on 2018-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20181212_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapName', models.CharField(max_length=255)),
                ('mapData', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
