# Generated by Django 2.1.4 on 2018-12-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_mapworld'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walkables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isWalkable', models.BooleanField(default=False)),
                ('velocity', models.FloatField(default=1)),
                ('colorId', models.CharField(blank=True, max_length=255)),
                ('effects', models.TextField(blank=True, null=True)),
                ('transform', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
