# Generated by Django 2.1.4 on 2018-12-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_walkables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FLOOR', 'Floor'), ('WALL', 'Wall'), ('CEIL', 'Ceil')], default='WALL', max_length=30)),
                ('imgBase', models.ImageField(null=True, upload_to='textures/')),
            ],
        ),
    ]
