# Generated by Django 2.1.4 on 2018-12-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_solids'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapworld',
            name='mapSolids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
