# Generated by Django 2.1.4 on 2018-12-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_mapworld_mapsolidsceil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('LEVELGATE', 'LevelGate'), ('DOOR', 'Door'), ('BUTTON', 'Button'), ('TRAP', 'Trap')], default='LEVELGATE', max_length=30)),
                ('icon', models.ImageField(null=True, upload_to='icons/')),
                ('imgBase', models.ImageField(null=True, upload_to='textures/')),
            ],
        ),
    ]
