# Generated by Django 2.1.4 on 2018-12-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_interactivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivos',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapworld',
            name='mapInteractivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapworld',
            name='scriptInteractivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
